name: Ejecutar Tests

# Define cu치ndo ejecutar el workflow (en este caso, al hacer "push" o "pull request" en la rama principal)
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# Define los "jobs" (tareas) que se ejecutar치n en el workflow
jobs:
  build-and-test:
    runs-on: ubuntu-latest # Usa un sistema Linux para ejecutar los tests

    steps:
      # 1. Clona el c칩digo del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configura Node.js en la m치quina virtual
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      # 3. Instala las dependencias
      - name: Install dependencies
        run: npm install

      # 4. Ejecuta los tests
      - name: Run tests
        run: npm test